### ISSUE TITLE
Exposed Nodes don't display name

### ISSUE THREAD

**Issue by Fire-wood** [monadgroup/axiom#11]
Exposed controls in group nodes with the 'show name' attribute checked don't have their names visible in the group node.

Edit: The 'show name' button functions on each individual control being named in the code, and not the node name which is somewhat confusing and counter-intuitive.

**Comment by cpdt** [comment]
How is it counter-intuitive? Controls have names, and nodes have names - they're different things and not the same. I'm guessing you're primarily referring to nodes with single controls, and I agree that there should be a solution to this. Not sure how it would look at the moment though.
