### ISSUE TITLE
Lighten Background Contrast

### ISSUE THREAD

**Issue by Fire-wood** [monadgroup/axiom#13]
With the current background, it's very difficult to identify the outlines of segments e.g. borders between windows, exit symbols of windows. A brighter contrast or background colour would be beneficial.

**Comment by cpdt** [comment]
What do you mean by "segments"?

**Comment by cpdt** [comment]
Going to mark this as a duplicate of #40 for now, since that's more inclusive of the rest of the UI (as opposed to just the background, which this is about).
