### ISSUE TITLE
Include example projects in downloads

### ISSUE THREAD

**Issue by cpdt** [monadgroup/axiom#134]

**Comment by piedoom** [comment]
Are there example sound files somewhere as well?  I'm sure users would love to listen to what's possible without needing a download :)

**Comment by cpdt** [comment]
@piedoom Really good idea. At the moment the example projects are just to demonstrate a few ways to actually build something in Axiom (so they're probably not great examples of what's possible if that makes sense, we threw them together pretty quick before the release), but we should have a few videos some time soon going more in-depth and allowing you to see/hear what's possible :)
