### ISSUE TITLE
Fix Mac build

### ISSUE THREAD

**Issue by cpdt** [monadgroup/axiom#142]
When building on macOS High Sierra with Xcode 10, the standalone editor immediately segfaults. This doesn't happen on the Windows builds however.

**Comment by remaininlight** [comment]
Thanks for posting up Axiom, looks promising and I am interested in trying it out. However, I am also experiencing this issue on macOS High Sierra with XCode 10.

When attempting to run I get:
```
Starting application
Using data path /Users/user/Library/Application Support/Axiom
Starting backend
Starting editor
LLVM ERROR: Program used external function '___bzero' which could not be resolved!

Process finished with exit code 1
```

I have tried adding:
```
jit->addBuiltin("__bzero", (uint64_t) & ::bzero);
```
To LLVMAxiomOrcCreateInstance in LLVMMaxim.cpp, which removes that error message but then the program hangs on launch. In my debugger it seems to be waiting on AxiomGUI::MainWindow::lockGlobalLibrary().

**Comment by cpdt** [comment]
@remaininlight Thanks! I'll have a look at the hang issue ASAP.

**Comment by cpdt** [comment]
Hi @remaininlight, the build should now be working on macOS. I've also added a macOS build to [the latest release](https://github.com/monadgroup/axiom/releases). Let me know if that works for you!

If the program is still hanging on `lockGlobalLibrary`, could you delete the `/Users/user/Library/Application Support/Axiom` directory? There might be a lock file there that Qt isn't cleaning up...

**Comment by remaininlight** [comment]
Thanks @cpdt, let the strange sounds begin! :)
