### ISSUE TITLE
SV Filter NaN Bug

### ISSUE THREAD

**Issue by Fire-wood** [monadgroup/axiom#169]
Increasing the 'Q' value on the SV filter beyond ~2 with both non-zero frequency and input values produces NaN, which requires deleting to fix.

**Comment by cpdt** [comment]
![image](https://user-images.githubusercontent.com/16081865/54056539-49547280-41e8-11e9-8af1-9667ef58e9a4.png)

This works fine for me? Are you sure you're feeding 2 in and not some large number, or something that's being converted to a Q value?
