### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by rdtor** [monadgroup/axiom#173]
hello, 
After struggling to compile with llvm 8 , i was succesfuull upto 96 % using llvm 6, I am getting this compile error.

/home/s***/Programs/axiom-0.4.3/editor/backend/vst2/AxiomVstPlugin.h:4:10: fatal error: public.sdk/source/vst2.x/audioeffectx.h: No such file or directory
 #include <public.sdk/source/vst2.x/audioeffectx.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [editor/backend/vst2/CMakeFiles/axiom_vst2_effect.dir/build.make:76: editor/backend/vst2/CMakeFiles/axiom_vst2_effect.dir/AxiomVstPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1005: editor/backend/vst2/CMakeFiles/axiom_vst2_effect.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by cpdt** [comment]
Hi, thanks for reporting the problem!

Yes, as said in [the build instructions](https://github.com/monadgroup/axiom#building), Axiom currently only works with LLVM 6.

The error you've specified seems to indicate you either forgot to provide the path to the VST2 SDK (as shown in the build instructions), or the path you've set is pointing to the wrong place.

The `VST2_SDK_ROOT` value provided to CMake should be the path of the folder in the VST SDK with the `pluginterfaces` and `public.sdk` folders.

Can you let me know if that resolves the problem?

**Comment by rdtor** [comment]
Hello thanks for your reply. Thank you for the suggestion I linked the vst2dk with the plugin interface and vst SDK to cmake and i was succesfull with the cmake, however when i run the build instruction i get the error at around 90 % completion

 95%] Linking CXX static library libaxiom_editor.a
[ 95%] Built target axiom_editor
Scanning dependencies of target axiom_vst2_effect
[ 96%] Building CXX object editor/backend/vst2/CMakeFiles/axiom_vst2_effect.dir/home/s***/Programs/steinberg-vst36/src/VST_SDK/VST2_SDK/public.sdk/source/vst2.x/audioeffect.cpp.o
In file included from /home/s***/Programs/steinberg-vst36/src/VST_SDK/VST2_SDK/public.sdk/source/vst2.x/audioeffect.h:37,
                 from /home/s***/Programs/steinberg-vst36/src/VST_SDK/VST2_SDK/public.sdk/source/vst2.x/audioeffect.cpp:35:
/home/s***/Programs/steinberg-vst36/src/VST_SDK/VST2_SDK/pluginterfaces/vst2.x/aeffect.h:158:32: error: expected ‘)’ before ‘*’ token
 typedef VstIntPtr (VSTCALLBACK *audioMasterCallback) (AEffect* effect, VstInt32 opcode, VstInt32 index, VstIntPtr value, void* ptr, float opt);

**Comment by rdtor** [comment]
Edit . i was successful in building the axiom_standalone version however the vst_instrument and vst_effects throws the same error

**Comment by cpdt** [comment]
Hi again! Yes, the standalone app does not depend on the VST SDK, but the VST instrument and effect plugins do. 

The error you’re getting looks like that file in the VST SDK is somehow corrupt or changed. Would you be able to specify the compiler you’re using and the relevant lines of the file in question?

**Comment by rdtor** [comment]
i am using gcc 8.3 as compiler that may be true my VST sdk file looks
corrupt, i am unable to compile the VST SDK from  git hub . I will try
compiling axiom after succesful VST SDK compilation

**Comment by cpdt** [comment]
Ah. The VST SDK on Github is the VST3 library, not VST2 (which Axiom depends on, as described in the readme). They aren't compatible.

You can download the VST2 SDK from Steinberg's website: http://steinberg.net/sdk_downloads/vstsdk366_27_06_2016_build_61.zip.

**Comment by rdtor** [comment]
I have tried with VST2 SDK from steinberg website and when i try to compile the SDK i get the error, i tried to link the VST2SDK folder without compiling and the error thrown are similar to my first post.

**Comment by rdtor** [comment]
Hi i had a bit of sucess in compiling axiom, i found that aeffect.h file inside the plugin interface folder needed to be patch from 
// ORIGINAL @ line 37

#elif defined(__GNUC__)
       #pragma pack(push,8)
       #define VSTCALLBACK __cdecl

// REPLACE @ line 37

#elif defined(__GNUC__)
       #pragma pack(push,8)
       #if defined(__linux__)
               #define VSTCALLBACK
       #else
               #define VSTCALLBACK __cdecl
       #endif

however now  i am getting this error

/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/crtbeginT.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/usr/bin/ld: final link failed: nonrepresentable section on output

**Comment by cpdt** [comment]
Glad to hear you got it working :)
