### ISSUE TITLE
Better UI color contrast

### ISSUE THREAD

**Issue by nnorm** [monadgroup/axiom#40]
I've tried your tool for a bit but I found myself struggling to dissociate some elements from each other and made selection harder. I think the UI would greatly benefit from more contrast between different elements and/or windows.
Another solution to this would be to add a color customization option but it'll probably need a lot of work.
Appart from that: it's very cool <3

**Comment by cpdt** [comment]
Hey, thanks for checking it out! You're definitely right, a lot of it is quite low-contrast. I'll add this to the 0.4.0 backlog, will see what I can do to improve it in the next few weeks.

**Comment by cpdt** [comment]
@nnorm Hey :)

I've played around with brightening the UI and increasing contrast, what do you think?

![image](https://user-images.githubusercontent.com/16081865/43999773-6b4d3f7e-9e56-11e8-9ce0-0e690886c965.png)

**Comment by nnorm** [comment]
Much better! :) 
Although I think it would be perfect if the header windows were a bit brighter than currently. But it's much more readable now, good job o/
