### ISSUE TITLE
Problem when trying to build

### ISSUE THREAD

**Issue by nnorm** [monadgroup/axiom#41]
I've tried to generate the projects from CMake but it gave me an error that stated it could not find "Qt5Widgets" package while I use the exact version you mentionned in the README.md.
Any idea how to fix that permanently?

**Comment by cpdt** [comment]
You'll probably need to provide CMake with a prefix path so it knows where to look for Qt - this would be the path to the folder with `bin`, `lib` and `include` directories installed by Qt. For example, with the regular installer you might specify a flag like `-DCMAKE_PREFIX_PATH=C:/Qt/5.11.0/msvc2017_32`.

**Comment by nnorm** [comment]
Problem solved! Thanks o/
