### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Fire-wood** [monadgroup/axiom#46]
The following actions were done which resulted in a crash. So far, these haven't been able to be reproduced.

#1:
A 'Multiply' was loaded onto the editor and it's code changed from 
`out:num = in:num * mul:num` to `out:num = in:num * mulone:num * multwo:num`
When this code attempted to compile, the program crashed

#2:
An 'Add Two' was dragged into a Group Node which caused the program to pause for a moment with the draggable cursor image still visible before crashing.

Edit:
#3:
Extracting an 'Add Two' output knob from a Group Node, connecting the extracted knob to another knob and then un-exposing the add two output node gives the following error:
"Access violation at address 0402A269 in module 'AxiomVST2.dll'. Read of address 00000008."
Attempting to add a 'Multiply' node then causes a crash.
Trying to reload the plugin may not work on first attempt after this.

**Comment by cpdt** [comment]
Did you have anything connected to the nodes? Were they extracted? In a group?

**Comment by cpdt** [comment]
Unfortunately I haven't been able to replicate the first or second crashes, and without more details I'll probably have to leave those until they're reproducible. If you're able to get them occurring consistently, let me know.

I am able to replicate the third crash however, so I'll add that to the 0.3.2 backlog.
