### ISSUE TITLE
0 value knob starting halfway

### ISSUE THREAD

**Issue by Fire-wood** [monadgroup/axiom#49]
Not entirely sure what is happening here, but the output of the multiply node is starting at 0, yet only begins halfway on the knob as if its values was 0.5. The previous nodes were
Sawtooth Gen -> Add Two (with +1 value) ->Multiply (with 0.5 value).

![omeda2](https://user-images.githubusercontent.com/29534646/43996869-b43086de-9e0f-11e8-99cd-1d12d98b02da.gif)

**Comment by cpdt** [comment]
This isn't a bug - you're feeding an oscillator value into the multiply input, so the output is also an oscillator value. Oscillator values are displayed in the range {-1, 1} on the knob.
