### ISSUE TITLE
Filter Issues

### ISSUE THREAD

**Issue by Fire-wood** [monadgroup/axiom#74]
The following filters don't work as expected:
- [x] The Peak Bi-quad Filter doesn't have any effect on the input signal
- [x] The State-Variable Filter outputs NaN when the input is non-zero and q is greater than 0.5.

**Comment by cpdt** [comment]
I've fixed the SV filter. Not sure what's up with the peak BQ filter, I can hear a slight change on the input but I'm not sure if it's actually doing what it should be...
