### ISSUE TITLE
Hold Module Causes Permanent Output

### ISSUE THREAD

**Issue by Fire-wood** [monadgroup/axiom#76]
Connecting a Hold module to an output with a Multiply hooked up (multiply set to 0), and then playing some notes causes the output to produce a constant volume. The work around is to disconnect something to make the whole synth reload which then removes the constant output (until played again).

**Comment by cpdt** [comment]
Can you please provide a minimal, verifiable project that demonstrates the bug? That will help in tracking it down.

**Comment by Fire-wood** [comment]
[broken.zip](https://github.com/monadgroup/axiom/files/2419476/broken.zip)

**Comment by cpdt** [comment]
Ah, so there isn't a bug here, but the surface is misconfigured:

![Misconfigured](https://user-images.githubusercontent.com/16081865/46123737-7416c400-c263-11e8-8ed8-2c39a7c8a6b2.png)

Notice which nodes have bold outlines. You're mixing down the results from each voice, and then re-extracted the mixed value and multiplying it, before feeding the extracted value into the audio output. You want this instead:

![Correct](https://user-images.githubusercontent.com/16081865/46123780-a2949f00-c263-11e8-9d1e-e15f25d575b3.png)

I can see how it's easy to make this mistake. If you have any suggestions for making extraction interactions clearer, that would be really good. At the moment, I'm considering using different colours for extracted connections (i.e connections with at least one end that's connected to an extracted node).
